### PR TITLE
Add small-spacer-tile

### PR DESCRIPTION
**Pull request by 2Grey**

### CODE REVIEW

**Comment by saada** [comment]
Thanks for your contribution... can you share a screenshot of the result? Thanks

**Comment by 2Grey** [comment]
@saada, 
[screenshoot](https://i.imgur.com/1xnGuiu.png)

**Review by saada — APPROVED** [review]
Thanks! LGTM

**Comment by saada** [comment]
I'll publish v1.1 soon

**Comment by saada** [comment]
Released on master. Also renamed the project since it works on macOS 10 and 11

**Pull request merged**
